
[build]
  base = "/"
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  CI = "false"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
